spring:
  application:
    name: car-dealer
  data:
    mongodb:
      host: localhost
      port: 27017

server:
  port: 8080
  servlet:
    contextPath: /rhdhv
  address: 127.0.0.1
  tomcat:
    accesslog:
      enabled: true
      buffered: false
      prefix: access
      suffix: .log
      pattern: common

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.hackerrank.stocktrades: DEBUG

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: healthcheck.html
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
  server:
    port: 8080
    address: 127.0.0.1
